name: cicd

on:
   push:
     branches:
       - main
jobs:
 
  build-and-deploy:
    name: myrepo
    runs-on: windows-latest
    steps:
 
      - name: Checkout Repository
        uses: actions/checkout@v3
